### ISSUE TITLE
.gitignore issue

### ISSUE THREAD

**Issue by Fallen-Breath** [Earthcomputer/JarModBuildTemplate#1]
In the .gitignore file here

https://github.com/Earthcomputer/JarModBuildTemplate/blob/8555ad1b961647d8b989892bd05252adebd9c98b/.gitignore#L37-L38

In addition to the `world` folder located in the root directory, it might ignore other folders with the name of `world` in non-root directories. e.g. `patches/net/minecraft/world`. Same to the `logs/` line

The solution is simple, just add some slash at the beginning of these lines, like what it is above

https://github.com/Earthcomputer/JarModBuildTemplate/blob/8555ad1b961647d8b989892bd05252adebd9c98b/.gitignore#L19-L23

**Comment by Fallen-Breath** [comment]
I don't know if the working directory of Minecraft will always be inside the root directory though. If it's variable, maybe those Minecraft files should be left to the users to handle themself

**Comment by Earthcomputer** [comment]
Whoops
